- name: Grab API Key
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - include_vars: 'vars.yml'
      no_log: 'yes'

    - name: Retrieve API Key
      panos_api_key:
        provider: '{{ provider }}'
      register: auth

    - name: Display API Key
      debug:
        var: '{{ auth.api_key }}'
        verbosity: 0
