- name: Demonstrate how to use OP module to execute various op commands on PANW device
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - include_vars: 'vars.yml'
      no_log: 'yes'

    - name: Show all interfaces using ('show interface all')
      panos_op:
        provider: '{{ provider }}'
        cmd: "show interface all"
      register: result

    - name: returned output in the default JSON format
      debug: msg='{{ result.stdout }}'

    - name: returned output in the XML format
      debug: msg='{{ result.stdout_xml }}'

    - name: Show system info op command
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: result

    - name: returned output in the XML format
      debug: msg='{{ result.stdout_xml }}'
